language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  - KOREBUILD_DNU_RESTORE_CORECLR=true KOREBUILD_TEST_DNXCORE=true
install:
  - curl -sSL https://github.com/libuv/libuv/archive/v1.4.2.tar.gz | tar zxfv - -C /tmp && cd /tmp/libuv-1.4.2/
  - sh autogen.sh
  - ./configure -prefix=$HOME/libuvinstall
  - make
  - make install
  - export LD_LIBRARY_PATH="$HOME/libuvinstall/lib"
  - cd $OLDPWD
mono:
  - 4.0.5
script:
  - ./build.sh --quiet verify
